---
# Ports for Redis master and slave
master_port: 6379
slave_port: 6379

# IP for master
master_ip: "{{ hostvars[groups['redismaster'][0]]['ansible_eth0']['ipv4']['address']  }}"

# Path for log file
redis_log: /var/log/redis/redis-server.log

# Dir for redis
redis_dir: /var/lib/redis

# Use append only file?
append_only: "no"

# Use sentinel? Working for CentOS 6.5 using remi... needs 2.8+ to be stable
sentinel: False

# Sentinel service
sentinel_service: redis-sentinel

# Path for sentinel log
sentinel_log: /var/log/redis/redis-sentinel.log

# Sentinel port
sentinel_port: 26379
