---
- name: Build Servers
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - group_vars/main.yml

  tasks:
    - name: Build your master
      local_action:
        module: rax
        credentials: "{{ creds_file }}"
        name: redis%01d
        flavor: "{{ rax_flavour }}"
        image: "{{ rax_image }}"
        state: present
        key_name: "{{ rax_key }}"
        count: 1
        count_offset: 1
        exact_count: yes
        group: redismaster
        wait: yes
      register: rax

    - name: Add the instances to the group 'redismaster'
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_user: root
        groupname: redismaster
      with_items: rax.success
      when: rax.action == 'create'

    - name: Build your slaves
      local_action:
        module: rax
        credentials: "{{ creds_file }}"
        name: redis%01d
        flavor: "{{ rax_flavour }}"
        image: "{{ rax_image }}"
        state: present
        key_name: "{{ rax_key }}"
        count: "{{ num_slaves }}"
        count_offset: 2
        exact_count: yes
        group: redisslaves
        wait: yes
      register: rax

    - name: Add the instances to the group 'redisslaves'
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_user: root
        groupname: redisslaves
      with_items: rax.success
      when: rax.action == 'create'

- name: Group by distro
  hosts: all:!localhost
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Install and configure redis for Ubuntu Hosts
  hosts: Ubuntu:Debian
  user: root
  roles:
    - roles/ubuntu
    - roles/common

- name: Install and configure redis for CentOS Hosts
  hosts: CentOS:RedHat
  user: root
  roles:
    - roles/centos
    - roles/common
